[package]
name = "rust-cpp-binding-example"
version = "0.1.0"
edition = "2021"

[lib]
name = "core"
crate-type = ["staticlib"]

[dependencies]
cxx = { version = "1.0.129" }

[build-dependencies]
cbindgen = "0.27.0"
